services:
#    todo_list.todo_repository:
#        factory
#        class: TodoListBundle\Repository\TodoRepository
#        factory-service: doctrine.orm.entity_manager
#        factory-method: getRepository
#        arguments:
#            - TodoListBundle\Entity\Todo
