TodoListBundle\Entity\Todo:
    type: entity
    table: task
    repositoryClass: TodoListBundle\Repository\TodoRepository
    id:
         id:
             type: guid
             generator: { strategy: UUID }
    fields:
        name:
            type: string
            length: 100
        isRead:
            type: boolean
        createdAt:
            type: datetime